pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Hub'
    repository: 'dbcawa/it-assets'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 'azure-pipeline-$(Build.BuildId)'

